### ISSUE TITLE
Architecture docker-image: arm64

### ISSUE THREAD

**Issue by Infusible** [acim/go-reflex#32]
Plz, add architecture -  arm64 
https://hub.docker.com/r/acim/go-reflex
` standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by acim** [comment]
I pushed new image both for amd64 and arm64. Please confirm if it works.

https://hub.docker.com/layers/acim/go-reflex/1.17.1/images/sha256-63d357f5722fdbc37372707cc94f64dfd4622a98dedd247659fa749a88da0863?context=repo

**Comment by Infusible** [comment]
oh, thx very much bro ,@acim
